before_script:
    - mkdir -p $GOPATH/src/gopkg.in
    - ln -s $CI_PROJECT_DIR $GOPATH/src/gopkg.in/stash
    - cd $GOPATH/src/gopkg.in/stash

stages:
    - build
    - test

test-go-1.9:
    image: golang:1.9
    stage: test
    script:
        - go get -v -t
        - go test -v

build-go-1.9:
    image: golang:1.9
    stage: build
    script:
        - go get -v
        - go build -v
